### ISSUE TITLE
PlugY

### ISSUE THREAD

**Issue by elvin-nsk** [zyel/zyel#10]
Can't figure out why plugy doesn't work.
I launch game via d2se.
Patch 11 from frozen keep runs ok.
But versions from here, plugy shows itself in title, but disappears from game.

**Comment by Moonpaw** [comment]
did you check "Use PlugY" in the d2se launcher?

**Comment by elvin-nsk** [comment]
Yes :)

**Comment by zyel** [comment]
copy pasty PlugY.log. maybe it will show something more. it should be in Mods/zyel as you use d2se

**Comment by xmontex** [comment]
copy-paste PlugY.log. maybe it will show something more. It should be in mods/zyel as you use d2se

**Comment by elvin-nsk** [comment]
Seems ok:
[PlugY.txt](https://github.com/zyel/zyel/files/41110/PlugY.txt)

**Comment by elvin-nsk** [comment]
But debuglog says "Couldn't parse horardric cube output!" many times

**Comment by xmontex** [comment]
those are ok... Set items cant be recognized during txt to bin conversion but they are recognized ingame. 
Plugy is NOT ok.
[PlugY.txt](https://github.com/zyel/zyel/files/41133/PlugY.txt) this is mine.
Maybe you have another copy of plugy in you diablo2 root directory and ini file was read from there?

**Comment by elvin-nsk** [comment]
Yes, i deleted it, same thing.

**Comment by elvin-nsk** [comment]
Also i reinstalled diablo - but it not help. Interesting, other mods in d2se works well with plugy, including zy-el 4.4 and zy-el 4.5 patch 11

**Comment by xmontex** [comment]
Try now (after updating). are there any changes?

**Comment by elvin-nsk** [comment]
No :(
If i understand it correctly, it happens only in my case? @Moonpaw said about same thing recently. If it's only mine, maybe it's windows 10 makes some mess between plugy and some other modder dll (although i run d2se in compatability mode). I even deleted pluggy's default ini's and log stays the same - probably pluggy loads its default settings from own dll or such (what mean "dll:" in log instead of "user:"?..).

I think, at last this problem may appear with more people, maybe it become clearer then. I'm not want you @xmontex  to focus on my particular case much, and thank you anyway!

**Comment by Moonpaw** [comment]
i too have the problem when i download the latest version from github. So its not unique to elvin

**Comment by sokol815** [comment]
I wonder if this is a similar line-endings error as existed in the .txt
files.

**Comment by xmontex** [comment]
Yay... Thanks gregbillings
it seems ini suffered the same fate as txt files. and plugy is picky
check now - should be fixed

**Comment by elvin-nsk** [comment]
Yes! It works! Thanks, guys! One thing, you need git to refresh ini files - i simply deleted them and make "revert" from Tortoise.
