### ISSUE TITLE
Raise Skeleton - Skill description insonsistency

### ISSUE THREAD

**Issue by ghost** [zyel/zyel#11]
Hello,
i noticed that there are different values (Damage and number of skeletons) on Summon Skeleton skill between skill tree and quick spell descriptions. Occurs even when i don't have any +skill items equipped.
Example:
![screenshot002](https://cloud.githubusercontent.com/assets/15469447/11325471/1d415264-914f-11e5-8952-f8b86d4910a1.jpg)
![screenshot003](https://cloud.githubusercontent.com/assets/15469447/11325472/1d6c739a-914f-11e5-8031-3e2982ea69a0.jpg)
EDIT: The correct values seems to be the skill tree description as i can have 7 skeletons.

**Comment by xmontex** [comment]
Fixed damage desc.
Can not do anything with number and next at.
