### ISSUE TITLE
Poison dmg is calculated strangely.

### ISSUE THREAD

**Issue by Moonpaw** [zyel/zyel#12]
Ok i dont get how poison dmg is calculated, i have a suspicion its calculated wrongly. Take the screenshots as reference

![screenshot012](https://cloud.githubusercontent.com/assets/15304869/11401833/c6c74da6-9394-11e5-830f-b63261be7b57.jpg)
![screenshot013](https://cloud.githubusercontent.com/assets/15304869/11401837/ce64bf58-9394-11e5-89e5-262ba9162e15.jpg)

**Comment by xmontex** [comment]
it IS calculated strangely... if you open any file that deals with poison damage you would see that they have completely different values than the ones on screen. values are in 256th per frame. you have to take the value, multiply it by 25 (as there are 25 frames per sec) and then divide by 256. wasted some valuable resources to do that conversion to display the damage per second. the old display was slightly wrong anyway...

**Comment by Moonpaw** [comment]
its causing me problems cause i wanted plague javelin to benefit from a 10th of your item min and max poison dmg. But turns out the "EMax" and "EMin" clumns are A) weird since the value i put in is not the actual value that will be in game and B) they dont accept formulas, at least not from me.

**Comment by xmontex** [comment]
a) could be solved but i see no way to solve b)

**Comment by Moonpaw** [comment]
its kinda sad cause it would be interesting to factor in elemental damage from equipment into skills.
