### ISSUE TITLE
Someone check that string table~

### ISSUE THREAD

**Issue by Moonpaw** [zyel/zyel#14]
![screenshot015](https://cloud.githubusercontent.com/assets/15304869/11430312/d70c8b72-9484-11e5-9d31-d08017d36e02.jpg)
![screenshot014](https://cloud.githubusercontent.com/assets/15304869/11430314/dd551148-9484-11e5-8789-8fa9ccd59f0b.jpg)

**Comment by xmontex** [comment]
fixed the two above
