### ISSUE TITLE
Error upon stepping into wilderness in Act V, hell

### ISSUE THREAD

**Issue by sokol815** [zyel/zyel#19]
The game ran into an error upon stepping into the wilderness in Act V. here it is:

[debuglog151202.txt](https://github.com/zyel/zyel/files/50413/debuglog151202.txt)

**Comment by sokol815** [comment]
happened again. looks like it may have to do with a lightning orb from the catapults?

**Comment by xmontex** [comment]
fixed

**Comment by sokol815** [comment]
awesome! You're really nailing it with the update speeds.
