### ISSUE TITLE
Hydra deals negative damage at high levels

### ISSUE THREAD

**Issue by sokol815** [zyel/zyel#20]
See screenshot. level 180 Hydra with +2891% fire damage
Increasing the Hydra level moves the minimum damage closer to 0. It is currently -46k.

![image](https://cloud.githubusercontent.com/assets/5951731/11648502/e34514cc-9d3a-11e5-99bf-34c9e17db84a.png)

**Comment by sokol815** [comment]
Chilling armor appears to have the same issue.

at level 177 it goes negative when 1 point is added
![image](https://cloud.githubusercontent.com/assets/5951731/11657753/7f21234c-9d84-11e5-8774-ac6a322045c2.png)

level 178:
![image](https://cloud.githubusercontent.com/assets/5951731/11657766/8db2fe76-9d84-11e5-83c6-2b3d9f637cbd.png)

but if you pull the point back off and it drops down to level 177 again, it is still negative:

and you have to re-equip another item to get it back into positive numbers.

**Comment by sokol815** [comment]
Also, I have %2783 to cold skill damage. Frost Nova, Ice bolt, and Shiver armor suffer the same fate.

**Comment by xmontex** [comment]
can you upload your save somewhere? Having trouble reproducing the issue.

**Comment by sokol815** [comment]
[Clytemnestra.txt](https://github.com/zyel/zyel/files/60179/Clytemnestra.txt)

note: the above txt file is actually a .d2s file, but it wouldn't let me upload it either in a zip file or as a .d2s file.

**Comment by xmontex** [comment]
should be fixed
