### ISSUE TITLE
too much gold?

### ISSUE THREAD

**Issue by Aragnir** [zyel/zyel#21]
drop from mobs, 500 gold from fallen. 95% extra gold. I use version from github(13.12.2015).

**Comment by xmontex** [comment]
At some time i increased dropped gold quantity by 8 times and decreased drop chance by 9 times. Picking all the small gold piles was rather tedious.
gold drop range from mobs is  level x1 to level x6. Fallen is lvl 9. Thus it could drop 9-54 gold. Now it can drop 72-432 gold. with 95% GF its 140-842.

**Comment by Aragnir** [comment]
Thank you.
