### ISSUE TITLE
Negative resistances on merc

### ISSUE THREAD

**Issue by ghost** [zyel/zyel#4]
Hi,
i don't know if it is feature or bug, but i find out that mercenary resistances goes down. My merc had -5 to all, now after a couple of levelups has -7.

**Comment by xmontex** [comment]
Players lose 1 of all resistances per level;
Mercenaries lose 0.5 of all resistances per level

in 4.4 players started with -100 and mercs with around -50. IMO that was kinda too much for act 1 and too little for act 5

**Comment by ghost** [comment]
Ok, thanks for info. Closing issue.
