### ISSUE TITLE
Battle orders not working right

### ISSUE THREAD

**Issue by Moonpaw** [zyel/zyel#5]
I just noticed with my barbarian that battle orders (the shout that increases life/mana stamina) doesnt work as displayed. I unequipped most of my gear and the skill was lvl 7 then. It shows a 53% life increase on the UI but when i used it my life went from 1250 to 1450 (which, according to math, isnt a 53% increase). And No, i dont have life% increasing gear on

**Comment by xmontex** [comment]
i guess its the way D2 calculates max life...
http://forums.d2jsp.org/topic.php?t=28710016
Thus life gain from "Increased vitality" passive skill (or any other sources that add +vit) is not affected by BO...

**Comment by Moonpaw** [comment]
I just did a test where i unequipped everything and removed all charms, i had about 490 life then, with BO that gives 38% in my case my life went to 570. Do the math, something is not right here. And dont blame it on increased vitality, thats not the issue.

**Comment by xmontex** [comment]
can you upload your save file somewhere? .d2s only
I would like to see your health values.
i did some quick testing with act switch and BO gave the amount of life the tooltip was telling: 1250 -> 1912 at lvl 7 (53%)
