### ISSUE TITLE
install process error

### ISSUE THREAD

**Issue by sokol815** [zyel/zyel#6]
Forked the repo, did a fresh d2 install, patched to d2 1.10, followed instructions on setup for the mod and ended up getting an error: Unhandled Exception: (c0000005)

d2 1.10 ran just fine before I installed the mod. are there any additional files that are needed?

**Comment by xmontex** [comment]
You can try using D2SE as the install process is much easier.
If you want to use standalone, then you will need to provide more details:
Do you see custom starting screen? Yes = good; No = wrong shortcut
When do you get this error? When you start the game / when you create character / other?
All errors are logged. Separate log is created each day (for today it would be D2151112.txt) in D2 root folder. It usually has more information than "Unhandled Exception". Can you upload it somewhere or dig out some additional details from it yourself?

**Comment by sokol815** [comment]
both methods of install failed for me. Not sure why. They both ended up with a similar error, but different stack dumps...

The game starts up just fine, but after attempting to enter a game with a new character, both crash.

debug logs:

downgrade to 1.10, create zyel folder, run d2modsetup.exe, create diablo II.exe shortcut, add parameters and change starting folder (followed instructions in the guide):
https://www.dropbox.com/s/i9ehpeal09r1008/NO_D2SE_D2151112.txt?dl=0

running under d2se:
https://www.dropbox.com/s/4ge79i2bou509ho/d2se_debuglog151112.txt?dl=0

I'd be happy to provide any other data you might need to troubleshoot this.

**Comment by xmontex** [comment]
11:05:40.453  Translating data from: skills
and then crash...

D2Common.#10578 - Load a bin file to memory OR loads a txt file and compiles to bin ->
Fog.dll.#10210 - get record count for the skills.txt table -> crash

but i cant tell you the cause of the crash... try checking your skills.txt - maybe it got corrupted during download, maybe you tried to edit it and saved it in some wrong format... That i do not know...

**Comment by sokol815** [comment]
thanks for the info. I directly saved the skills.txt from the repository here into my copy... still got the same error after starting.

did some troubleshooting:
replaced skills.txt with skills.bin from 4.5v11, got an error on itemtypes.txt instead
replaced itemtypes.txt with itemtypes.bin from 4.5v11, got an error on itemstatcost.txt instead
replaced itemstatcost.txt with itemstatcost.bin from 4.5v11, got an error on properties.txt instead
then missiles.txt,
...
states.txt
monstats.txt
skilldesc.txt
charstats.txt
...

I am running under windows 7 64bit as administrator.
I noticed on the forums another user got the exact same error (http://d2mods.info/forum/viewtopic.php?p=480004#p480004)

it's obviously having trouble loading certain .txt files. I am not sure why it is able to load and convert the 14 files before it[EDIT: because they are just copied from an mpq somewhere, not converted from .txt format], but dies on the skills.txt file, because it had no trouble interpreting all those other .txt files before it...

I've been looking around to see if there is an independent .txt to bin converter for diablo 2, but I couldn't find any evidence thereof.

edit:
just noticed that all the .bins it was able to create were files that did not have a corresponding .txt in the mod... in which case I assume they are just being extracted from a .mpq somewhere.

**Comment by xmontex** [comment]
no idea how to reproduce the crash :(
it fails to crash on my computer...
Included all the bin files. You should be able to play the mod by removing -txt switch from shortcut but you wont be able to change anything.

**Comment by sokol815** [comment]
Interesting. Not sure if you use the tool d2excel or not, but you can attempt to open skills.txt using d2excel and it will only get the first few columns of the first row and quit. meanwhile, if you grab a clean skills.txt from the d2_patch.mpq file, it opens correctly. It seems like there is some formatting issue inside of the skills.txt (and possibly all .txt files) in this repo.

Some testing with d2excel:
armor.txt from the repo: loads the entire file as if it were a single row.
armor.txt from clean 1.10 txt files: loads as expected.

I'm beginning to think the entire issue is line endings...

Did some further checking using sublimeText2 to change the line endings from unix to dos/windows on skills.txt...

attempted to run zyel again and it successfully parsed the skills.txt file.

The issue is with the line-ending encoding on the .txt files, looks like diablo 2 requires it to be dos/windows line endings and not unix line endings.

This also explains why only some users are getting the issue. It is dependent upon the checkout configuration in git... lots of people use convert to system line endings, others use check out as-is. In this case, I just downloaded the repo, so I assume that the repo has them saved with unix line endings.

**Comment by sokol815** [comment]
You may want to add the following to your .gitattributes file to force text files into crlf:

```
# Declare files that will always have CRLF line endings on checkout.
*.txt text eol=crlf
```

**Comment by xmontex** [comment]
thanks for clearing this out. Can you redownload and check if adding gitattributes solved the problem?
Btw are you sokol815 on d2mods.info forums or is anyone else struggling with similar problem?

**Comment by sokol815** [comment]
Hey, that did it. I cloned again, deleted all the included bins and ran zyel. I was able to create a new character and move things into/out of stash, save, load again.

I think you can remove the bins from the download again, as they bloat the project by quite a bit.

I am sokol815 from the forums. Thanks for all your help, xmontex!
