### ISSUE TITLE
Auras granted by sets

### ISSUE THREAD

**Issue by Moonpaw** [zyel/zyel#7]
to make it shorts, they dont work. At least the ones i tested (Hsarus and Civerb's) I fully equipped them one by one (with my barb if that matters) and the effects were not granted. Playing the update 11 version. Maybe it has been fixed by now. I cant get any build from the github to run anyway

**Comment by sokol815** [comment]
Hey Moonpaw, an update was just posted yesterday that actually fixes zyel to be able to run... have you tried checking it out since yesterday evening?

**Comment by Moonpaw** [comment]
can anyone give me a clear instruction on what to do to mod the latest github version AND get to play it? because i once pulled a complete repository from github and i just couldnt get it to run, it threw an exception every time. Btw add Milebrega's to the list of sets that grant an aura in the description but dont actually do so

**Comment by Moonpaw** [comment]
i know how to edit the txt files and all that, but as soon as i try to run it, it crashes

**Comment by sokol815** [comment]
do you have d2se installed? if so, you can just drop the directory that contains plugY, data, docs... etc. into the 'MODS' folder, start up d2se and go. This mod had trouble building for people up until yesterday, when it was fixed.

So you have MODS -> zyel -> (plugY, data, docs... etc.)

Have you tried to run it before you edited anything using d2se?

**Comment by Moonpaw** [comment]
nope, and i tried it like 3 weeks ago, before that fix you mentioned.

**Comment by Moonpaw** [comment]
Just tried it, same problem, i load a new character, d2 assertion error and crash

**Comment by sokol815** [comment]
1. Please confirm if you are using d2se or not.
2. Can you please attach the debug log for today titled 'debuglog151114.txt' which is inside the zyel folder so we can see what the error message is?

**Comment by Moonpaw** [comment]
1) i am using d2se
[debuglog151114.txt](https://github.com/zyel/zyel/files/34740/debuglog151114.txt)

**Comment by sokol815** [comment]
It is having trouble finding killCounter.bin, that needs to be made by converting killCounter.txt to killCounter.bin You have to tell Diablo 2 it needs to compile files from .txt to bin, and to read those files. You can do that by clicking 2 checkboxes in the bottom right corner of d2se for the zyel mod.

See red rectangle below

![startup](https://cloud.githubusercontent.com/assets/5951731/11165728/aae92272-8add-11e5-8530-9b7282109136.png)

**Comment by Moonpaw** [comment]
it works now, i can load a character, but PlugY doesnt work at all (its missing, even though i checked use Plugy in d2se) and barbarian is missing one of his passive skills

**Comment by Moonpaw** [comment]
it also seems as if its using the original vanilla LOD skills now
EDIT: nvm, D2SE couldve told me it cant compile the txt files when theyre still opened by another program

**Comment by Moonpaw** [comment]
Back to the original problem: It worked when i used the same sets with my necromancer or his mercanary
maybe it was a fluke when it didnt work? i dont know. Someone else should test it too

**Comment by xmontex** [comment]
tested with latest github version. auras seem to work fine. fixed some small issue related to hsarus set (not related to auras though)

**Comment by elvin-nsk** [comment]
PlugY doesnt work for me too.
