### ISSUE TITLE
Barbarian cant dual wield two handed swords anymore

### ISSUE THREAD

**Issue by Moonpaw** [zyel/zyel#8]
As the title says, yeah

**Comment by Moonpaw** [comment]
While i figured out how to fix it myself now, you guys should look into it
the column M "1or2handed" needs to be 1 for 2 handed swords that should be able to be dual wielded for barbs

**Comment by xmontex** [comment]
I removed that last year for some reason. I think, i wanted to limit 1h weapons to 5 sockets max but then dropped the idea. Will fix swords and war hammer once i have some free time

**Comment by xmontex** [comment]
fixed
