### ISSUE TITLE
BUG: Platinum dragon death sometimes causes crash

### ISSUE THREAD

**Issue by Moonpaw** [zyel/zyel#9]
In the world stone keep (so far in level 1) sometimes i get an assertion error and game crash when i kill platinum drakes/dragons, after i land the final blow but before i see their death animation. Maybe someone can test it out

**Comment by Moonpaw** [comment]
screenshot of the error here:
![asseertion error](https://cloud.githubusercontent.com/assets/15304869/11313492/80c74884-8fdd-11e5-9c68-74c3263af825.png)

**Comment by xmontex** [comment]
!DDTHTH.cof is completely messed up :(

**Comment by Moonpaw** [comment]
what is completely messed up???

**Comment by xmontex** [comment]
commited new cof just now. you can test and tell if the crashes still exist.
i ran through the keep and matrix without any crashes.

but if you are interested... !D is platinum dragon code; DT meant death animation; HTH - weapon class. cof most likely translates into control file. Frankly speaking its a file that controls dragons death animation... 

Edit... still getting crashes :(
Edit2... Updated other cofs as well.

**Comment by xmontex** [comment]
Is anyone still getting crashes on platinum dragon death?
